# Generated by Django 2.2 on 2020-07-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Auth_name', models.CharField(max_length=10)),
                ('Auth_Section', models.CharField(max_length=20)),
            ],
        ),
    ]
