# Generated by Django 3.1.1 on 2020-09-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apiapp', '0003_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='Buyer_id',
            field=models.IntegerField(),
        ),
    ]
